#!/usr/bin/env python
import os
import sys

env = SConscript("../../godot-cpp/SConstruct")

env_pp = env.Clone()
# 添加供编译器查看的包含目录
env_pp.Append(CPPPATH=["."])
# 预编译头文件
env_pp.Append(CXXFLAGS=['/FI"pp.h"'])

# 添加'src'目录下所有.cpp文件
sources = []
for root, dirs, files in os.walk('.'):
    for f in files:
        if f.endswith('.cpp'):
            sources.append(root + '/' + f)

# thirdpart - steam
env_pp.Append(CPPPATH=["../thirdparty/steamworks"])
env_pp.Append(LIBPATH=["../project/bin"])
env_pp.Append(LIBS=["steam_api64"])

# out
library = env_pp.SharedLibrary(
    "../project/bin/{}{}{}".format("game_gdextension", env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)
