#!/usr/bin/env python
import os
import sys

Import('env')

env_pp = env.Clone()

# 添加供编译器查看的包含目录
env_pp.Append(CPPPATH=["."])

# 添加'src'目录下所有.cpp文件
sources = []
for root, dirs, files in os.walk('.'):
    for f in files:
        if f.endswith('.cpp'):
            sources.append(root + '/' + f)

env_pp.add_source_files(env.modules_sources, sources)
