#!/usr/bin/env python
import os
import sys

env = SConscript("../../godot-cpp/SConstruct")

# 添加供编译器查看的包含目录
env.Append(CPPPATH=["."])

# 添加'src'目录下所有.cpp文件
sources = []
for root, dirs, files in os.walk('.'):
    for f in files:
        if f.endswith('.cpp'):
            sources.append(root + '/' + f)

library = env.SharedLibrary(
    "../project/bin/{}{}{}".format("ppgame", env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)